name: boilerplate
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  intl: ^0.17.0
  get: ^4.6.5
  get_storage: ^2.0.3
  metooltip: ^0.0.7
  shared_preferences: ^2.0.13
  google_maps_flutter: ^2.1.3
  google_maps_flutter_web: ^0.3.2+1
  google_maps_webservice: ^0.0.19
  flutter_google_places: ^0.3.0
  map_picker: ^0.0.3
  timelines: ^0.1.0
  currency_text_input_formatter: ^2.1.5
  image_picker_web: ^2.1.1
  bs_flutter_selectbox: ^1.3.0
  flutter_gallery_3d: ^1.0.4
  table_calendar: ^3.0.6
  date_time_format: ^2.0.1
  file_picker: ^4.6.1
  zefyrka: ^1.3.0
  fl_chart: ^0.55.1

  bs_flutter_buttons: 
    path: ./modules/bs_flutter_buttons
  bs_flutter_datatable: 
    path: ./modules/bs_flutter_datatables
  bs_flutter_modal: 
    path: ./modules/bs_flutter_modal
  # bs_flutter_selectbox: 
  #   path: ./modules/bs_flutter_selectbox
  bs_flutter_inputtext:
    path: ./modules/bs_flutter_inputtext
  bs_flutter_responsive:
    path: ./modules/bs_flutter_responsive

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/ventes-logo.png
    - assets/images/logo-short.png
    - assets/images/bg_auth.png
    - assets/images/location.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Monseratt
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
